//! Stage agent JAR + platform native lib into OUT_DIR and generate `embedded_assets.rs`.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let emb = out_dir.join("embedded");
    fs::create_dir_all(&emb).expect("create OUT_DIR/embedded");

    println!("cargo:rerun-if-env-changed=JAVAR_EMBED_AGENT");
    println!("cargo:rerun-if-env-changed=JAVAR_EMBED_NATIVE");
    println!("cargo:rerun-if-changed=../javar-agent/target");
    println!("cargo:rerun-if-changed=../target/release");
    println!("cargo:rerun-if-changed=../target/debug");

    let agent_dst = emb.join("javar-agent.jar");
    let mut has_agent = false;
    match find_agent_jar(&manifest_dir) {
        Some(src) => {
            fs::copy(&src, &agent_dst).unwrap_or_else(|e| {
                panic!("copy agent {} -> {}: {e}", src.display(), agent_dst.display())
            });
            println!("cargo:warning=embedding agent from {}", src.display());
            has_agent = true;
        }
        None => {
            fs::write(&agent_dst, []).expect("write empty agent stub");
            println!(
                "cargo:warning=javar-agent.jar not found at build time — \
                 embed stub is empty. Build agent first: cd javar-agent && mvn -DskipTests package"
            );
        }
    }

    let native_name = native_lib_filename();
    let native_dst = emb.join(native_name);
    let mut has_native = false;
    match find_native_lib(&manifest_dir, native_name) {
        Some(src) => {
            fs::copy(&src, &native_dst).unwrap_or_else(|e| {
                panic!("copy native {} -> {}: {e}", src.display(), native_dst.display())
            });
            println!("cargo:warning=embedding native lib from {}", src.display());
            has_native = true;
        }
        None => {
            fs::write(&native_dst, []).expect("write empty native stub");
            println!(
                "cargo:warning={} not found at build time — build javar-core --release first",
                native_name
            );
        }
    }

    // Generate include paths with forward slashes (Windows-safe for include_bytes!).
    let agent_lit = path_literal(&agent_dst);
    let native_lit = path_literal(&native_dst);
    let gen = format!(
        r#"// @generated by build.rs — do not edit
pub const EMBEDDED_AGENT: &[u8] = include_bytes!(r"{agent_lit}");
pub const EMBEDDED_NATIVE: &[u8] = include_bytes!(r"{native_lit}");
pub const NATIVE_NAME: &str = "{native_name}";
pub const HAS_EMBEDDED_AGENT: bool = {has_agent};
pub const HAS_EMBEDDED_NATIVE: bool = {has_native};
"#
    );
    fs::write(out_dir.join("embedded_assets.rs"), gen).expect("write embedded_assets.rs");
}

fn path_literal(p: &Path) -> String {
    p.to_string_lossy().replace('\\', "/")
}

fn native_lib_filename() -> &'static str {
    if cfg!(target_os = "windows") {
        "javar_core.dll"
    } else if cfg!(target_os = "macos") {
        "libjavar_core.dylib"
    } else {
        "libjavar_core.so"
    }
}

fn find_agent_jar(manifest_dir: &Path) -> Option<PathBuf> {
    if let Ok(p) = env::var("JAVAR_EMBED_AGENT") {
        let p = PathBuf::from(p);
        if p.is_file() {
            return Some(p);
        }
    }

    let roots = [
        manifest_dir.join("../javar-agent/target"),
        manifest_dir.join("../../javar-agent/target"),
        manifest_dir.join("embedded"),
    ];

    for dir in roots {
        if let Some(jar) = pick_agent_jar(&dir) {
            return Some(jar);
        }
    }
    None
}

fn pick_agent_jar(dir: &Path) -> Option<PathBuf> {
    let rd = fs::read_dir(dir).ok()?;
    let mut jars: Vec<PathBuf> = rd
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| {
            p.extension().and_then(|e| e.to_str()) == Some("jar")
                && p.file_name()
                    .and_then(|n| n.to_str())
                    .map(|n| {
                        let l = n.to_ascii_lowercase();
                        l.contains("javar-agent")
                            && !l.contains("sources")
                            && !l.contains("javadoc")
                            && !l.contains("original")
                    })
                    .unwrap_or(false)
        })
        .collect();
    jars.sort();
    jars.pop()
}

fn find_native_lib(manifest_dir: &Path, name: &str) -> Option<PathBuf> {
    if let Ok(p) = env::var("JAVAR_EMBED_NATIVE") {
        let p = PathBuf::from(p);
        if p.is_file() {
            return Some(p);
        }
    }

    let triple = env::var("TARGET").unwrap_or_else(|_| env::var("HOST").unwrap_or_default());
    let candidates = [
        manifest_dir.join("../target/release").join(name),
        manifest_dir.join("../target/debug").join(name),
        manifest_dir.join(format!("../target/{triple}/release/{name}")),
        manifest_dir.join(format!("../target/{triple}/debug/{name}")),
        manifest_dir.join("embedded").join(name),
    ];

    candidates.into_iter().find(|p| p.is_file())
}
